name = "My name is Addison"
number = "7"
number =  "250"
breakfast = "I had nothing for breakfast"
color = "My favorite color is maroon"
school = "Ucas"
year = "2024"
eye = "My eyes are brown"   
age =   "I am 14"
subjuct = "My favorite subject is biology"
print(name, number, number, breakfast, color, school, year, eye, age, subjuct)
