name = print("My name is Addison")
number = print("7")
number =  print("250")
breakfast = print("I had nothing for breakfast")
color = print("My favorite color is maroon")
school = print("Ucas")
year = print("2024")