name = input("Type your name: ")
place = input("Type a place: ")
verb = input("Type a verb: ")
noun = input("Type a noun: ")
sentenenceOne = input(" went to the ")
sentenenceTwo = input(" where they")
sentenenceThree = input(" and bought a")
print(name, sentenenceOne, place, sentenenceTwo, verb, sentenenceThree, noun)